name: pgpool

services:
  ansible:
    build: ./ansible
    volumes:
      - ./ansible:/workspace
    working_dir: /workspace
    entrypoint:
      - tail
      - -f
      - /dev/null

  client:
    build: ./client
    entrypoint:
      - tail
      - -f
      - /dev/null
    
  node:
    build: ./database
    user: postgres
    command:
      - postgres
      - -cconfig_file=/configs/postgres.conf
      - -chba_file=/configs/pg_hba.conf
    volumes:
      - /var/lib/postgresql/data/pgdata
      - ./database/configs:/configs:ro
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    healthcheck:
      test: 'pg_isready -U postgres --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          # cpus: '0.01'
          memory: 2G
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
