name: pgpool

x-node-template: &node-template
  build: ./database
  user: postgres
  command:
    - -cconfig_file=/configs/postgres.conf
    - -chba_file=/configs/pg_hba.conf
  volumes:
    - /var/lib/postgresql/data/pgdata
    - ./database/configs:/configs:ro
  healthcheck:
    test: 'pg_isready'
    interval: 10s
    timeout: 5s
    retries: 5
  deploy:
    resources:
      limits:
        memory: 2G
  networks:
    - postgres-net

x-master-template: &master-template
  <<: *node-template
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres123
  
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 2G

x-slave-template: &slave-template
  <<: *node-template
  environment: &node-envs
    PGDATA: /var/lib/postgresql/data/pgdata

    MASTER_HOST: postgres-proxy
    MASTER_PORT: 25433
    MASTER_REPLICATOR_USER: replicator
    MASTER_REPLICATOR_PASSWORD: replicator123
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 2G

services:
  ansible:
    build: ./ansible
    volumes:
      - ./ansible:/workspace
    working_dir: /workspace
    # entrypoint:
    #   - tail
    #   - -f
    #   - /dev/null
    entrypoint:
      - ansible-playbook
      - -i
      - inventory.yaml
      - playbook.yaml
    networks:
      - postgres-net
    depends_on:
      - node-1

  client:
    build: ./client
    # entrypoint:
    #   - tail
    #   - -f
    #   - /dev/null
    ports:
      - 8089:8089
    volumes:
      - ./client:/app
    depends_on:
      - node-1
      - node-2
      - node-3
    networks:
      - proxy-net

  node-1:
    <<: *master-template
    volumes:
      - node-1:/var/lib/postgresql/data
      - ./database/configs:/configs:ro
      - ./database/scripts:/ha-scripts:ro
      - ./database/health_check.sh:/health_check.sh:ro

  node-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.17.1
    environment:
      DATA_SOURCE_URI: "postgres-proxy:25433/postgres?sslmode=disable"
      DATA_SOURCE_USER: "monitor"
      DATA_SOURCE_PASS: "monitor123"
      
      PG_EXPORTER_EXTEND_QUERY_PATH: /queries.yaml
    volumes:
      - ./node-exporter/queries.yaml:/queries.yaml:ro
    ports:
      - "9187:9187"
    depends_on:
      - postgres-proxy
    networks:
      - proxy-net

  ha-watcher:
    image: postgres:17.4-bookworm
    user: postgres
    entrypoint:
      - tail
      - -f
      - /dev/null
    environment:
      PGHOST: node-1
      PGPORT: 5432
      PGUSER: monitor
      PGPASSWORD: monitor123
    volumes:
      - ./ha-watcher/scripts:/scripts:ro
      - ./ha-watcher/sql:/sql:ro
    networks:
      - postgres-net

  node-2:
    <<: *slave-template
    environment: 
      <<: *node-envs
      NODE_NAME: node_2
    volumes:
      - node-2:/var/lib/postgresql/data
      - ./database/configs:/configs:ro

  node-3:
    <<: *slave-template
    environment: 
      <<: *node-envs
      NODE_NAME: node_3
    volumes:
      - node-3:/var/lib/postgresql/data
      - ./database/configs:/configs:ro
  
  node-4:
    <<: *slave-template
    environment: 
      <<: *node-envs
      NODE_NAME: node_4
    volumes:
      - node-4:/var/lib/postgresql/data
      - ./database/configs:/configs:ro

  postgres-proxy:
    build: ./nginx
    ports:
      - "6433:5433"   # Postgres node 1
      - "6434:5434"   # Postgres node 2
      - "6435:5435"   # Postgres node 3
      - "6436:5436"   # Postgres node 4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/streams:/etc/nginx/streams:ro
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4
    networks:
      - proxy-net
      - postgres-net

networks:
  postgres-net:
  proxy-net:

volumes:
  node-1:
  node-2:
  node-3:
  node-4:

