name: pgpool

x-node-template: &node-template
  build: ./database
  user: postgres
  command:
    - postgres
    - -cconfig_file=/configs/postgres.conf
    - -chba_file=/configs/pg_hba.conf
  volumes:
    - /var/lib/postgresql/data/pgdata
    - ./database/configs:/configs:ro
  healthcheck:
    test: 'pg_isready -U postgres --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5
  deploy:
    resources:
      limits:
        memory: 2G
  networks:
    - postgres-net

x-master-template: &master-template
  <<: *node-template
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres123
  
  deploy:
    resources:
      limits:
        memory: 2G

x-slave-template: &slave-template
  <<: *node-template
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata

    MASTER_HOST: postgres-proxy
    MASTER_PORT: 25433
    MASTER_REPLICATOR_USER: replicator
    MASTER_REPLICATOR_PASSWORD: replicator123
  deploy:
    resources:
      limits:
        cpus: '0.01'
        memory: 2G

services:
  ansible:
    build: ./ansible
    volumes:
      - ./ansible:/workspace
    working_dir: /workspace
    # entrypoint:
    #   - tail
    #   - -f
    #   - /dev/null
    entrypoint:
      - ansible-playbook
      - -i
      - inventory.yaml
      - playbook.yaml
    networks:
      - postgres-net
    depends_on:
      - node-1

  client:
    build: ./client
    entrypoint:
      - tail
      - -f
      - /dev/null
    networks:
      - proxy-net

  node-1:
    <<: *master-template
    volumes:
      - node-1:/var/lib/postgresql/data
      - ./database/configs:/configs:ro
  
  node-2:
    <<: *slave-template
    volumes:
      - node-2:/var/lib/postgresql/data
      - ./database/configs:/configs:ro

  node-3:
    <<: *slave-template
    volumes:
      - node-3:/var/lib/postgresql/data
      - ./database/configs:/configs:ro

  postgres-proxy:
    build: ./nginx
    ports:
      - "6433:5433"   # Postgres node 1
      - "6434:5434"   # Postgres node 2
      - "6435:5435"   # Postgres node 3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/streams:/etc/nginx/streams:ro
    depends_on:
      - node-1
      - node-2
      - node-3
    networks:
      - proxy-net
      - postgres-net

networks:
  postgres-net:
  proxy-net:

volumes:
  node-1:
  node-2:
  node-3:
