
- name: "hello world"
  hosts: bastion
  tasks:
    - debug:
        msg: "Hello, World!"
    - community.postgresql.postgresql_ping:
        login_host: "{{ item }}"
        login_db: postgres
        login_user: postgres
        login_password: postgres123
      loop: "{{ nodes }}"
