
- name: "Check connectivity to Postgres nodes"
  hosts: bastion
  vars_files:
    - vars.yaml
  environment: &posgres_envs
    PGDATABASE: postgres
    PGUSER: postgres
    PGPASSWORD: "{{ POSTGRES_PASSWORD }}"
  tasks:
    - community.postgresql.postgresql_ping:
        login_host: "{{ item }}"
      loop: "{{ nodes }}"
- name: Setup master node
  hosts: bastion
  vars_files:
    - vars.yaml
  environment: *posgres_envs
  tasks:
    - name: Create replicator user
      community.postgresql.postgresql_user:
        login_host: "{{ master_node }}"

        name: replicator
        password: "{{ REPLICATOR_PASSWORD }}"
        role_attr_flags: REPLICATION
    - name: Create database benchmark_db
      community.postgresql.postgresql_db:
        login_host: "{{ master_node }}"
        name: benchmark_db
        comment: "Benchmark database for performance testing"
